# Generated by Django 3.1.4 on 2021-02-18 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0002_auto_20210211_0645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['date_create']},
        ),
        migrations.AlterModelTable(
            name='news',
            table='news',
        ),
    ]
