# Generated by Django 3.1.4 on 2021-02-20 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0003_auto_20210218_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='news_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app_news.news', verbose_name='новость'),
        ),
    ]
